language: java
jdk: oraclejdk8
sudo: required
dist: trusty
services:
  - docker
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

env:
  matrix:
    - VERSIONS_TO_BUILD=4
    - VERSIONS_TO_BUILD=5
    - VERSIONS_TO_BUILD=6

# https://github.com/travis-ci/travis-ci/issues/8667
install: true

script: travis_wait 60 ./gradlew -PrepoName=docker.io/xenit check --info

deploy:
  provider: script
  script: travis_wait 30 ./gradlew -PrepoName=docker.io/xenit pushDockerImage
  skip_cleanup: true
  on:
    branch: master
