version: '3.2'

services:
 alfresco:
   image: ${DOCKER_IMAGE}
   ports:
     - 8080
     - 8443
   depends_on:
     - postgresql
   environment:
   - SOLR_HOST=solr
   - GLOBAL_legacy.transform.service.enabled=false
   - GLOBAL_local.transform.service.enabled=false
   - APPLICATIONLOG_MAXDAYS=1

