version: '3.2'

services:
 alfresco-pdf-renderer:
   image: alfresco/alfresco-pdf-renderer:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 libreoffice:
   image: alfresco/alfresco-libreoffice:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 imagemagick:
   image: alfresco/alfresco-imagemagick:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 # only works from Alfresco 6.1 on
 tika:
   image: alfresco/alfresco-tika:1.2
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 # only works from Alfresco 6.1 on
 transform-misc:
   image: alfresco/alfresco-transform-misc:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host
