version: '3'

services:
  alfresco:
     image: ${DOCKER_IMAGE}
     environment:
       - GLOBAL_messaging.subsystem.autoStart=true
       - "GLOBAL_messaging.broker.url=failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
       - GLOBAL_local.transform.service.enabled=false
       - GLOBAL_transform.service.enabled=true
       - GLOBAL_transform.service.url=http://transform-router:8095
       - GLOBAL_sfs.url=http://shared-file-store:8099/     
  transform-router:
     image: quay.io/alfresco/alfresco-transform-router:1.1.0
     environment:
        JAVA_OPTS: " -Xms256m -Xmx512m"
        ACTIVEMQ_URL: "nio://activemq:61616"
        IMAGEMAGICK_URL: "http://imagemagick:8090"
        PDF_RENDERER_URL : "http://alfresco-pdf-renderer:8090"
        LIBREOFFICE_URL : "http://libreoffice:8090"
        TIKA_URL : "http://tika:8090"
        MISC_URL : "http://transform-misc:8090"
        FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
  shared-file-store:
     image: alfresco/alfresco-shared-file-store:0.5.3
     environment:
        JAVA_OPTS: " -Xms256m -Xmx512m"
        scheduler.content.age.millis: 86400000
        scheduler.cleanup.interval: 86400000
     volumes:
        - shared-file-store-volume:/tmp/Alfresco/sfs
  activemq:
     image: alfresco/alfresco-activemq:5.15.8
     ports:
       - 8161:8161 # Web Console
       - 5672:5672 # AMQP
       - 61616:61616 # OpenWire
       - 61613:61613 # STOMP

volumes:
    shared-file-store-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs