version: '3'

services:
 alfresco-pdf-renderer:
   image: alfresco/alfresco-pdf-renderer:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"

 libreoffice:
   image: alfresco/alfresco-libreoffice:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"

 imagemagick:
   image: alfresco/alfresco-imagemagick:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"

 # only works from Alfresco 6.1 on
 tika:
   image: alfresco/alfresco-tika:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"

 # only works from Alfresco 6.1 on
 tika:
   image: alfresco/alfresco-transform-misc:2.1.0
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"


