version: '3.2'

services:
 alfresco-pdf-renderer:
   image: alfresco/alfresco-pdf-renderer:4.0.0@sha256:28bf5d258ba9572b5c5e09ca04b2e859b03b0cdfaa774a0d8fb85466d3ebaa30
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 libreoffice:
   image: alfresco/alfresco-libreoffice:4.0.0@sha256:9bb89e6b84cac57ad48b74d4d34a3d2f4b8a9b19cdc67f6afed25e561e957a3f
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 imagemagick:
   image: alfresco/alfresco-imagemagick:5.1.7@sha256:ed4e4a20d9f8d69a154c52a71aaedcdec61145542d6fc79cbdb51268617a1071
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 # only works from Alfresco 6.1 on
 tika:
   image: alfresco/alfresco-tika:1.3@sha256:80c9fcc7f053938b521da7bdeeb0e8751f821f31f7b49666c9359f6bda4ad1bf
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 # only works from Alfresco 6.1 on
 transform-misc:
   image: alfresco/alfresco-transform-misc:4.0.0@sha256:958558bca43294e9a21fce6f937d8c633bb700ea03d5217bcb136e098d813737
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host
