version: '3.2'

services:

 postgresql:
   image: ${PSQL_IMAGE:-docker.io/xenit/postgres:13@sha256:d9c3e2a7c41c668835adb8752b17ad1506dcd38744a0c67ca90699a7be4b7e80}
   environment:
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=admin
   - POSTGRES_DB=alfresco


