version: '3.2'

services:
 alfresco-pdf-renderer:
   image: alfresco/alfresco-pdf-renderer:2.6.0@sha256:db4f71c7c4edba330391f71e8f7881f44188851d53c1714e26a9c1586749d164
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 libreoffice:
   image: alfresco/alfresco-libreoffice:2.6.0@sha256:bfba2ce0efa9e0d7978a58e5c0c3cee29816dd70df7a345c31b500666c1afa76
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 imagemagick:
   image: alfresco/alfresco-imagemagick:2.6.0@sha256:545c4f2d24b82ef547c79561e71d1d693688798bcf1546901ea5750c341a4b3e
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 # only works from Alfresco 6.1 on
 tika:
   image: alfresco/alfresco-tika:1.3@sha256:80c9fcc7f053938b521da7bdeeb0e8751f821f31f7b49666c9359f6bda4ad1bf
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 # only works from Alfresco 6.1 on
 transform-misc:
   image: alfresco/alfresco-transform-misc:2.6.0@sha256:ebe36babe53a165de78d2f66046bfa9e9a802a1c716ec46c0d4f5579b6e1f465
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host
