version: '3.2'

services:
 alfresco-pdf-renderer:
   image: alfresco/alfresco-pdf-renderer:4.0.0@sha256:28bf5d258ba9572b5c5e09ca04b2e859b03b0cdfaa774a0d8fb85466d3ebaa30
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 libreoffice:
   image: alfresco/alfresco-libreoffice:4.0.0@sha256:9bb89e6b84cac57ad48b74d4d34a3d2f4b8a9b19cdc67f6afed25e561e957a3f
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 imagemagick:
   image: alfresco/alfresco-imagemagick:4.0.0@sha256:6be4b9ea43081d083bfe933fd0796339e004c4d5ddbce36350a38c0840be2386
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 # only works from Alfresco 6.1 on
 tika:
   image: alfresco/alfresco-tika:1.3@sha256:80c9fcc7f053938b521da7bdeeb0e8751f821f31f7b49666c9359f6bda4ad1bf
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host

 # only works from Alfresco 6.1 on
 transform-misc:
   image: alfresco/alfresco-transform-misc:2.6.0@sha256:ebe36babe53a165de78d2f66046bfa9e9a802a1c716ec46c0d4f5579b6e1f465
   environment:
     JAVA_OPTS: " -Xms256m -Xmx512m"
   ports:
     - target: 8090
       mode: host
