evaluationDependsOn(':tomcat-base')

subprojects {
    apply plugin: 'eu.xenit.docker'
    apply plugin: 'eu.xenit.docker-alfresco'
    apply plugin: 'eu.xenit.docker-compose'

    if (new File("${project.projectDir}/overload.gradle").exists())
        apply from: "${project.projectDir}/overload.gradle"

    def tomcatProject = project(getTomcatProject(project.alfresco.version.major))
    def tomcatImage = tomcatProject.getTasks().getByName('buildDockerImage')
    println "tomcatImage: ${tomcatImage.getImageId()}"

    dockerBuild {
        repositories = [calcRepository(project.alfresco.flavor, true)]
        tags = calcTags(project.alfresco.version)
    }

    createDockerFile {
        smartCopy "${project.parent.projectDir}/src/shared/main/bash/entrypoint/docker-entrypoint.d/", '/docker-entrypoint.d/'
        dependsOn(tomcatImage)
        baseImage = tomcatImage.getImageId()
        volume('/opt/alfresco/alf_data')
        environmentVariable('ALFRESCO_VERSION', "${project.alfresco.version.major}.${project.alfresco.version.minor}.${project.alfresco.version.rev}")
        environmentVariable('ALFRESCO_FLAVOR', "${project.alfresco.version.flavor}")
        environmentVariable('ALFRESCO_ENABLED', "true")
        //TODO: make shared logging map, put in base properties files and 90 script and read out where necessary
        if (project.alfresco.version.major == 7 && project.alfresco.version.minor <= 3) {
            environmentVariable('LOG4J_VERSION', '1')
            smartCopy(file("${project.rootDir}/logging/templates/log4j1.properties"), "/log4j.properties.base")
        } else {
            environmentVariable('LOG4J_VERSION', '2')
            smartCopy(file("${project.rootDir}/logging/templates/log4j2.properties"), "/log4j.properties.base")
        }
    }

    // Disable pull because base image is built locally and not pushed to a repo
    buildDockerImage.pull = false
}
