ARG BASE_IMAGE=docker.io/xenit/tomcat:alfresco-7.0-ubuntu
FROM $BASE_IMAGE

# named volumes
VOLUME 	/opt/alfresco/alf_data ${CATALINA_HOME}/temp ${CATALINA_HOME}/logs

HEALTHCHECK --interval=10s --timeout=3s --retries=30 --start-period=20s CMD curl --max-time 4 -f http://localhost:${TOMCAT_PORT}/alfresco/s/api/server || exit 1

ARG ALFRESCO_VERSION_MAJOR
ARG ALFRESCO_VERSION_MINOR
ARG ALFRESCO_VERSION_REV
ENV ALFRESCO_VERSION ${ALFRESCO_VERSION_MAJOR}.${ALFRESCO_VERSION_MINOR}.${ALFRESCO_VERSION_REV}

ARG ALFRESCO_FLAVOR
ENV ALFRESCO_FLAVOR ${ALFRESCO_FLAVOR}

ARG XENIT_VERSION
LABEL eu.xenit.docker.docker-alfresco.version=$XENIT_VERSION

# start ALF will be done by java image's entrypoint + tomcat image's CMD
