name: 'Continuous Integration'
on: [ push, pull_request, workflow_dispatch ]

env:
  ORG_GRADLE_PROJECT_alfresco_nexus_username: ${{ secrets.ALFRESCO_NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_alfresco_nexus_password: ${{ secrets.ALFRESCO_NEXUS_PASSWORD }}

jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 6
          - 7
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Write build date
        run: "mkdir -p ~/.gradle && echo 'buildDate='$(date +%s) >> ~/.gradle/gradle.properties"
      - name: Login to Xenit docker registry
        env:
          DOCKER_USER: ${{ secrets.XENIT_DOCKER_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.XENIT_DOCKER_REGISTRY_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login hub.xenit.eu --username "$DOCKER_USER" --password-stdin
      - name: Login to CloudSmith docker registry
        env:
          DOCKER_USER: ${{ secrets.CLOUDSMITH_USER }}
          DOCKER_PASSWORD: ${{ secrets.CLOUDSMITH_APIKEY }}
        run: echo "$DOCKER_PASSWORD" | docker login docker.xenit.eu --username "$DOCKER_USER" --password-stdin
      - name: Run integration tests
        env:
          VERSIONS_TO_BUILD: ${{ matrix.version }}
        run: ./gradlew integrationTests --info
        # We have to split out publishing to public and private repo's because pushing to docker.io does not seem to work
        # without supplying DOCKER_USER and DOCKER_PASSWORD. However, supplying those environment variables breaks
        # publishing to other repositories
      - name: Publish public docker images
        if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release') }}
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSIONS_TO_BUILD: ${{ matrix.version }}
        run: ./gradlew pushDockerImage -PincludeEnterprise=false
      - name: Publish private docker images
        if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release') }}
        env:
          VERSIONS_TO_BUILD: ${{ matrix.version }}
        run: ./gradlew :2repository:pushDockerImage -PincludeCommunity=false
