name: 'Continuous Integration'
on:
  push:
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_alfresco_nexus_username: ${{ secrets.ALFRESCO_NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_alfresco_nexus_password: ${{ secrets.ALFRESCO_NEXUS_PASSWORD }}

jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Write build date
        run: "mkdir -p ~/.gradle && echo 'buildDate='$(date +%s) >> ~/.gradle/gradle.properties"
      - name: Login to CloudSmith docker registry
        uses: docker/login-action@v2
        with:
          registry: private.docker.xenit.eu
          username: ${{ secrets.CLOUDSMITH_USER }}
          password: ${{ secrets.CLOUDSMITH_APIKEY }}
      - name: Unit tests
        run: ./gradlew test --parallel --info -Penterprise
      - name: Build image and Run integration tests
        run: ./gradlew integrationTests --info -Penterprise
      - name: Upload Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: /home/runner/work/**/build/reports
          retention-days: 2
        # We have to split out publishing to public and private repo's because pushing to docker.io does not seem to work
        # without supplying DOCKER_USER and DOCKER_PASSWORD. However, supplying those environment variables breaks
        # publishing to other repositories
      # - name: Publish public docker images
      #   if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release') }}
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_USER }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     VERSIONS_TO_BUILD: ${{ matrix.version }}
      #   run: ./gradlew pushDockerImage -PincludeEnterprise=false
      - name: Publish private docker images
        if: ${{ github.ref == 'refs/heads/ethias' }}
        run: ./gradlew -Penterprise -Plegacy pushDockerImage
