name: 'Continuous Integration'
on: [push, pull_request, workflow_dispatch]

env:
  ORG_GRADLE_PROJECT_alfresco_nexus_username: ${{ secrets.ALFRESCO_NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_alfresco_nexus_password: ${{ secrets.ALFRESCO_NEXUS_PASSWORD }}

jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       version:
        - 6
        - 7
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Write build date
      run: "mkdir -p ~/.gradle && echo 'buildDate='$(date +%s) >> ~/.gradle/gradle.properties"
    - name: Login to Xenit docker registry
      env:
        DOCKER_USER: ${{ secrets.XENIT_DOCKER_REGISTRY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.XENIT_DOCKER_REGISTRY_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login hub.xenit.eu --username "$DOCKER_USER" --password-stdin
    - name: Login to CloudSmith docker registry
      env:
        DOCKER_USER: ${{ secrets.CLOUDSMITH_USER }}
        DOCKER_PASSWORD: ${{ secrets.CLOUDSMITH_APIKEY }}
      run: echo "$DOCKER_PASSWORD" | docker login docker.xenit.eu --username "$DOCKER_USER" --password-stdin
    - name: Login to Docker hub registry
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
    - name: Run integration tests
      env:
       VERSIONS_TO_BUILD: ${{ matrix.version }}    
      run: ./gradlew -PrepoName=docker.io/xenit integrationTests --info
    - name: Publish docker images
      env:
       VERSIONS_TO_BUILD: ${{ matrix.version }}
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: ./gradlew pushDockerImage
