# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
       version:
        - 4
        - 5
        - 6

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Write build date
      run: "mkdir -p ~/.gradle && echo 'buildDate='$(date +%s) >> ~/.gradle/gradle.properties"
    - name: Run integration tests
      env:
       VERSIONS_TO_BUILD: ${{ matrix.version }}    
      run: ./gradlew -PrepoName=docker.io/xenit check --info
    - name: Push images
      env:
       VERSIONS_TO_BUILD: ${{ matrix.version }}            
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: ./gradlew -PrepoName=docker.io/xenit pushDockerImage
